# Generated by Django 3.2.11 on 2022-01-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='get_can_pause',
            new_name='guest_can_pause',
        ),
    ]
